import = [
    # "~/.config/alacritty/catppuccin_mocha.toml",
    # "~/.config/alacritty/challenger_deep.toml",
    # "~/.config/alacritty/dawn_fox.toml",
    # "~/.config/alacritty/day_fox.toml",
    # "~/.config/alacritty/gruvbox_light.toml",
    "~/.config/alacritty/gruvbox_dark.toml",
    # "~/.config/alacritty/hyper.toml",
    # "~/.config/alacritty/zenburn.toml",
    # "~/.config/alacritty/minischeme_light.toml",
    # "~/.config/alacritty/miniautumn_dark.toml",
    # "~/.config/alacritty/kanagawa.toml",
    # "~/.config/alacritty/tokyonight.toml",
    # "~/.config/alacritty/zenbones_light.toml",
    # "~/.config/alacritty/zenbones_dark.toml",
]

[font]
size = 8.5

[font.normal]
family = "Terminess Nerd Font"
# family = "JetBrains Mono"
# family = "SourceCode Pro"



